#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Test script for MineContext Analysis API
Demonstrates how to retrieve and analyze historical data
"""

import requests
import json
from datetime import datetime, timedelta


# Configuration
API_URL = "http://localhost:8765"
AUTH_TOKEN = "default_token"
HEADERS = {"Authorization": f"Bearer {AUTH_TOKEN}"}


def test_two_weeks_data():
    """Test: Get all data from past two weeks"""
    print("=" * 60)
    print("TEST 1: Get Two Weeks Data")
    print("=" * 60)
    
    response = requests.get(
        f"{API_URL}/api/analysis/two-weeks-data",
        headers=HEADERS
    )
    
    if response.ok:
        data = response.json()['data']
        stats = data['statistics']
        
        print(f"✅ Successfully retrieved two weeks data")
        print(f"\n📊 Statistics:")
        print(f"  - Reports: {stats['total_reports']}")
        print(f"  - Activities: {stats['total_activities']}")
        print(f"  - Todos: {stats['total_todos']} (Completed: {stats['completed_todos']}, Pending: {stats['pending_todos']})")
        print(f"  - Tips: {stats['total_tips']}")
        print(f"  - Date Range: {stats['date_range']['start'][:10]} to {stats['date_range']['end'][:10]}")
        
        # Show sample report
        if data['reports']:
            print(f"\n📄 Sample Report:")
            report = data['reports'][0]
            print(f"  - ID: {report['id']}")
            print(f"  - Created: {report['created_at']}")
            print(f"  - Content Length: {len(report.get('content', ''))} chars")
        
        return data
    else:
        print(f"❌ Error: {response.status_code} - {response.text}")
        return None


def test_daily_summary(days=7):
    """Test: Get daily summary"""
    print("\n" + "=" * 60)
    print(f"TEST 2: Get Daily Summary ({days} days)")
    print("=" * 60)
    
    response = requests.get(
        f"{API_URL}/api/analysis/daily-summary?days={days}",
        headers=HEADERS
    )
    
    if response.ok:
        data = response.json()['data']
        daily_summary = data['daily_summary']
        
        print(f"✅ Successfully retrieved daily summary for {data['total_days']} days")
        print(f"\n📅 Daily Breakdown:")
        
        for day in daily_summary[:7]:  # Show first 7 days
            print(f"  {day['date']}:")
            print(f"    - Reports: {len(day['reports'])}")
            print(f"    - Activities: {len(day['activities'])}")
            print(f"    - Todos: {len(day['todos'])}")
            print(f"    - Tips: {len(day['tips'])}")
        
        return daily_summary
    else:
        print(f"❌ Error: {response.status_code} - {response.text}")
        return None


def test_weekly_stats(weeks=2):
    """Test: Get weekly statistics"""
    print("\n" + "=" * 60)
    print(f"TEST 3: Get Weekly Statistics ({weeks} weeks)")
    print("=" * 60)
    
    response = requests.get(
        f"{API_URL}/api/analysis/weekly-stats?weeks={weeks}",
        headers=HEADERS
    )
    
    if response.ok:
        data = response.json()['data']
        weekly_stats = data['weekly_stats']
        
        print(f"✅ Successfully retrieved weekly stats for {data['total_weeks']} weeks")
        print(f"\n📈 Weekly Comparison:")
        
        for week in weekly_stats:
            print(f"\n  Week {week['week_number']} ({week['week_start'][:10]} to {week['week_end'][:10]}):")
            print(f"    - Reports: {week['total_reports']}")
            print(f"    - Activities: {week['total_activities']} ({week['total_activity_hours']} hours)")
            print(f"    - Todos: {week['total_todos']} (Completed: {week['completed_todos']})")
            print(f"    - Completion Rate: {week['completion_rate']}%")
        
        return weekly_stats
    else:
        print(f"❌ Error: {response.status_code} - {response.text}")
        return None


def test_save_analysis():
    """Test: Save analysis result"""
    print("\n" + "=" * 60)
    print("TEST 4: Save Analysis Result")
    print("=" * 60)
    
    analysis_data = {
        "analysis_type": "two_weeks_summary",
        "content": f"""# Two Weeks Analysis Report

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Summary
This is a test analysis result generated by the analysis API.

## Key Findings
- Data collected from past 2 weeks
- Multiple reports and tips generated
- System is functioning normally

## Recommendations
- Continue monitoring daily activities
- Review weekly trends
- Optimize content generation
""",
        "metadata": {
            "generated_by": "test_script",
            "version": "1.0"
        },
        "start_time": (datetime.now() - timedelta(days=14)).isoformat(),
        "end_time": datetime.now().isoformat()
    }
    
    response = requests.post(
        f"{API_URL}/api/analysis/save-result",
        headers=HEADERS,
        json=analysis_data
    )
    
    if response.ok:
        data = response.json()['data']
        print(f"✅ Analysis result saved successfully")
        print(f"  - Document ID: {data['doc_id']}")
        print(f"  - Message: {data['message']}")
        return data['doc_id']
    else:
        print(f"❌ Error: {response.status_code} - {response.text}")
        return None


def main():
    """Run all tests"""
    print("\n🚀 Starting MineContext Analysis API Tests\n")
    
    try:
        # Test 1: Two weeks data
        two_weeks_data = test_two_weeks_data()
        
        # Test 2: Daily summary
        daily_summary = test_daily_summary(days=7)
        
        # Test 3: Weekly statistics
        weekly_stats = test_weekly_stats(weeks=2)
        
        # Test 4: Save analysis
        doc_id = test_save_analysis()
        
        print("\n" + "=" * 60)
        print("✅ All tests completed successfully!")
        print("=" * 60)
        print("\n📝 Available API Endpoints:")
        print("  1. GET  /api/analysis/two-weeks-data")
        print("  2. GET  /api/analysis/daily-summary?days=N")
        print("  3. GET  /api/analysis/weekly-stats?weeks=N")
        print("  4. POST /api/analysis/save-result")
        print("\n💡 Use these endpoints to analyze historical data from MineContext!")
        
    except requests.exceptions.ConnectionError:
        print("\n❌ Error: Cannot connect to MineContext API")
        print("Please ensure MineContext is running on http://localhost:8765")
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")


if __name__ == "__main__":
    main()
